"""Make username unique

Revision ID: b12e174e667e
Revises: ca8b22568181
Create Date: 2026-08-28 12:02:14.914255

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b12e174e667e"
down_revision: str | Sequence[str] | None = "ca8b22568181"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.create_unique_constraint("uq_username", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.drop_constraint("uq_username")
    # ### end Alembic commands ###
