"""Add timestamp columns

Revision ID: ca8b22568181
Revises: 4ef237e9f17e
Create Date: 2026-08-27 12:43:21.935312

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca8b22568181"
down_revision: str | Sequence[str] | None = "4ef237e9f17e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("created", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("updated", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("last_login", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_login")
    op.drop_column("user", "updated")
    op.drop_column("user", "created")
    # ### end Alembic commands ###
